import argparse
import collections
import math
import sys

from dataclasses import dataclass
from matplotlib import pyplot as plt


@dataclass
class Round:
    desc: str
    round_success_rate: float


# Generated by the following command:
# tools/count_distillation_cost --end-to-end-success-rate=0.289314677
# See also:
# https://docs.google.com/spreadsheets/d/1NV1PXI3OCJHO0QLHeb4nQcJ7v9jxXbYIJyWrJgQPSQg/edit?gid=1498708646#gid=1498708646
ENTRIES: list[Round] = [
    Round(desc='Encode T', round_success_rate=1.0),
    Round(desc='Stablize', round_success_rate=0.820),
    Round(desc='Check T', round_success_rate=1.0),
    Round(desc='Check T', round_success_rate=0.893),
    Round(desc='Stabilize', round_success_rate=0.864),
    Round(desc='Stabilize', round_success_rate=0.953),
    Round(desc='Stabilize', round_success_rate=0.943),
    Round(desc='Escaped!', round_success_rate=0.964),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=1.0),
    Round(desc='[Wait for gap]', round_success_rate=0.528),
    Round(desc='ready', round_success_rate=1.0),
]


def desc(n: float) -> str:
    power = math.floor(math.log10(n))
    while 10**(power + 1) <= n:
        power += 1
    base = round(n / 10**power * 10) / 10
    base = str(base).ljust(3, '0')
    return fr'${base} \cdot 10^{{{power}}}$'


def plot_series(
        ax: plt.Axes,
        series: list[Round],
        *,
        label: str | None = None) -> None:
    labels = [r.desc for r in series]
    ax.set_xticks(range(len(labels) + 1), [''] * (len(labels) + 1))
    ax.set_xticks([i + 0.5 for i in range(len(labels))], labels, rotation=90, minor=True)
    ax.xaxis.set_tick_params(length=0, which='minor')

    xs: list[float] = [0]
    ys: list[float] = [1]
    prob = 1.0
    for (i, round) in enumerate(series):
        xs.append(i + 1)
        ys.append(prob)
        prob *= round.round_success_rate
        xs.append(i + 1)
        ys.append(prob)

    ax.plot(xs, ys, label='Survival Probability', color='C0')
    ax.fill_between(xs, [0 for _ in ys], ys, alpha=0.2, color='C0')


def main():
    parser = argparse.ArgumentParser(description='description')
    parser.add_argument('--out', type=str, default=None)

    args = parser.parse_args()
    if args.out is None:
        print('The output filename should be specified via --out.', file=sys.stderr)
        sys.exit(1)
    output_filename = args.out

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.set_xlim(0, len(ENTRIES))
    ax.set_ylabel('Survival Probability')
    ax.set_ylim(0, 1.01)

    plot_series(ax, ENTRIES)

    ax.grid(which='major', color='#BBBBBB')

    fig.tight_layout()
    fig.savefig(output_filename)


if __name__ == '__main__':
    main()
